apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: llama-server
  namespace: default
spec:
  selector:
    matchLabels:
      app: llama-server
  template:
    metadata:
      labels:
        app: llama-server
    spec:
      hostNetwork: true
      containers:
        - name: llama-server
          image: ghcr.io/sage-liuzx/llama-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "2"
              memory: "2Gi"
            limits:
              cpu: "4"
              memory: "4Gi"
