apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: predictor-feedback-pvc
  namespace: llama-scheduler
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: predictor-model-pvc
  namespace: llama-scheduler
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
